version: "3.2"

services:
  frontend:
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  apigateway:
    ports:
      - 8888:443

  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672

  postgres: 
    ports:
      - 5432:5432

  eventstore:
    ports:
      - 1113:1113
      - 2113:2113