version: "3.2"

services:
  frontend:
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672

  postgres: 
    ports:
      - 5432:5432