version: "3.2"

services:
  frontend:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 

  apigateway:
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 

  command-service:
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 

  identity-service:
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 

  query-service:
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 

  command-handler:
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 

  rabbitmq:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 

  postgres:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 

  eventstore:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 

  jaeger:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    resources:
      limits:
        cpus: '0.5'
        memory: 350M
      reservations:
        cpus: '0.1'
        memory: 100M 
