version: "3.2"

services:
  apigateway:
    image: rsww/apigateway:${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - backend
    ports:
      - 8080:443
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASS}
    depends_on:
      - command-service
      - identity-service
      - query-service

  command-service:
    image: rsww/command-service:${TAG:-latest}
    build:
      context: .
      dockerfile: CommandService/Dockerfile
    networks:
      - backend

  identity-service:
    image: rsww/indentity-service:${TAG:-latest}
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    networks:
      - auth_db
      - backend
    depends_on:
      - postgres

  query-service:
    image: rsww/query-service:${TAG:-latest}
    build:
      context: .
      dockerfile: QueryService/Dockerfile
    networks:
      - backend
    expose:
      - "1113"
      - "2113"
    depends_on:
      - eventstore.db

  command-handler:
    image: rsww/command-handler:${TAG:-latest}
    build:
      context: .
      dockerfile: CommandHandler/Dockerfile
    networks:
      - backend
    expose:
      - "1113"
      - "2113"
    depends_on:
      - rabbitmq
      - eventstore.db

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    networks:
      - backend
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      - auth_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s

  eventstore.db:
    image: eventstore/eventstore:21.2.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      - backend
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore


volumes:
  local_postgres_data: {}
  eventstore-volume-data:
  eventstore-volume-logs:

networks:
  auth_db:
  backend: